// Generated by CoffeeScript 1.6.2
$(function() {
  var difference, leftSplashWidth, rightSplashWidth;

  if ($.browser.msie && ($.browser.version === '8.0' || $.browser.version === '7.0')) {
    $('#splash').append('<img id="ie_left_splash" src="/images/elements/skeletor/ie_playbuttons_left.png"/>');
    $('#splash').append('<img id="ie_right_splash" src="/images/elements/skeletor/ie_playbuttons_right.png"/>');
    $('#drain').css('background', "#3ea9f5 url('/images/elements/skeletor/drain_buttons.png') no-repeat bottom center");
    leftSplashWidth = 700;
    rightSplashWidth = 750;
    if (leftSplashWidth + rightSplashWidth > $('#section-1').width()) {
      difference = (leftSplashWidth + rightSplashWidth) - $('#section-1').width();
      $('#ie_left_splash').css('left', 0 - (difference / 2));
      return $('#ie_right_splash').css('right', 0 - (difference / 2));
    }
  } else {
    $('#top_canvas_wrapper').append('<canvas id="home_animation"></canvas>');
    return $('#bottom_canvas_wrapper').append('<canvas id="bottom_animation"></canvas>');
  }
});

$(window).load(function() {
  return setTimeout(function() {
    var $kinguser, $kingvideo;

    wistiaPlaylist.bind("play", function() {
      return $("#differentiators .textOverlay").hide();
    });
    wistiaPlaylist.bind("end", function() {
      return wistiaPlaylist.bind("afterembed", function(sectionIndex, videoIndex) {
        var $li;

        $li = $("#differentiators .tabs>li").eq(videoIndex);
        $("#differentiators .tabs>li").removeClass("selected").trigger("remove-class");
        $li.addClass("selected").trigger("add-class");
        return this.unbind;
      });
    });
    $kingvideo = $("#differentiators .differentiators_video_wrapper");
    $kinguser = $("#usecases .marsbar.kingsize");
    $('#usecases .user').mouseover(function() {
      return $(this).addClass('hover');
    });
    $('#usecases .user').mouseout(function() {
      return $(this).removeClass('hover');
    });
    $('#usecases .user').each(function() {
      var $highlighteduser, userclass;

      $highlighteduser = $(this);
      userclass = $highlighteduser.attr('data-user');
      $highlighteduser.bind("select-user", function() {
        $('.selected_user').children().hide();
        $('.selected_user').children().find('.callout').css('bottom', '');
        $('.selected_user').find('.' + userclass).show();
        $('.selected_user').find('.' + userclass).find('.callout').show();
        $kinguser.removeClass('mailchimp_bar');
        $kinguser.removeClass('seomoz_bar');
        $kinguser.removeClass('blanklabel_bar');
        $kinguser.removeClass('alltimate_bar');
        return $kinguser.addClass("" + userclass + "_bar");
      });
      return $highlighteduser.click(function() {
        $('#usecases .user').removeClass('active');
        $(this).addClass('active');
        $highlighteduser.trigger("select-user");
        return false;
      });
    });
    return $(function() {
      var $vid_container, $video, respondVideo;

      $("#differentiators .tabs>li").each(function(i) {
        var $a, $li, $textOverlay, myClass, selectme;

        $li = $(this);
        $a = $li.find('a');
        myClass = $a.text();
        $textOverlay = $li.closest("#differentiators").find(".textOverlay." + myClass);
        $li.bind("remove-class", function() {
          $li.removeClass('selected');
          return $kingvideo.removeClass(myClass);
        });
        $li.bind("add-class", function() {
          $li.addClass('selected');
          return $kingvideo.addClass(myClass);
        });
        selectme = function() {
          $('#differentiators li').trigger('remove-class');
          $li.trigger('add-class');
          $li.closest('#differentiators').find('.textOverlay').hide();
          return $textOverlay.show();
        };
        return $li.click(function() {
          selectme();
          wistiaPlaylist.embed(0, i, {
            autoPlay: false
          });
          return false;
        });
      });
      $video = $('.wistia_embed');
      $vid_container = $($video).closest('.inner_container');
      respondVideo = function() {
        var width;

        width = $($vid_container).width();
        return wistiaPlaylist.width(width).constrainToWidth();
      };
      respondVideo();
      return $(window).resize(respondVideo);
    });
  }, 1);
});